[package]
name = "database"
version = "0.1.0"
description = "This library is responsible for starting the DB server, and making it accessible"
edition = "2021"

[dependencies]
surrealdb = "2.0.1"
once_cell = "1.19.0"
dotenvy = "0.15.7"
tracing = "0.1.41"